basic:
  seed: 233
  GPU: 0
  debug: False
  id: 'unnamed'
  mode: train
  search: False
  amp: 'O1'

experiment:
  name: 'AnnotatedRandomKTrainTestSplit'
  random_state: 233
  run_fold: -1
  batch_sampler: False
  weight: False
  preprocess: JPEG_512_pan
  image_only: True
  skip_outlier: True
  outlier: train
  anno_only: False
  keep_valid: True

data:
  mask_prefix: 'segmentations_pl2_768'
  full_mask: True

model:
  name: 'eb5_unet'
  from_checkpoint: './weights/stage2_models/B5_768_stage2/eb5_s2_fold{}_best_score.pth'
  out_feature: 11
  params:
    dropout: 0.5
    pretrained: True
    pool: gem

train:
  dir: '../results'
  batch_size: 14
  num_epochs: 24
  cutmix: True
  beta: 1
  cutmix_prob: 0.75
  cutmix_prob_increase: 0
  validations_round: 1
  freeze_backbond: 1
  freeze_top_layer_groups: 0
  freeze_start_epoch: 1

eval:
  batch_size: 32

loss:
  name: 'bce'
  seg_weight: 40
  params:
#    eps: 0.1
    reduction: 'none'

optimizer:
  name: 'Adam'
  step: 1
  params:
    lr: 0.0008
    weight_decay: 0

scheduler:
  name: 'CosineAnnealingLR'
  warm_up: True
  params:
    factor: 0.2
    patience: 10

transform:
  name: 's_0220/0220_hf_cut_0.5_768'
#  val_name: 'sin_valid_512'
  num_preprocessor: 12
  size: 768
