basic:
  seed: 233
  GPU: 0
  debug: False
  id: 'unnamed'
  mode: train
  search: False
  amp: 'Native'

experiment:
  name: 'AnnotatedRandomKTrainTestSplit'
  random_state: 233
  run_fold: -1
  batch_sampler: False
  weight: False
  preprocess: JPEG_512_pan
  image_only: True
  skip_outlier: True
  outlier: train
  anno_only: False
  keep_valid: True

data:
  image_prefix: 'png_512'

model:
  name: 'v2m_aux'
  from_checkpoint: 'none'
  out_feature: 4
  params:
    dropout: 0.5
    pretrained: True
    pool: gem

train:
  dir: '../results'
  batch_size: 24
  num_epochs: 24
  cutmix: True
  beta: 1
  cutmix_prob: 0.75
  cutmix_prob_increase: 0
  validations_round: 1
  freeze_backbond: 1
  freeze_top_layer_groups: 0
  freeze_start_epoch: 1

eval:
  batch_size: 32

loss:
  name: 'label_smooth_ce'
  seg_weight: 40
  params:
    eps: 0.1
    reduction: 'none'

optimizer:
  name: 'Adam'
  step: 1
  params:
    lr: 0.0004
    weight_decay: 0

scheduler:
  name: 'CosineAnnealingLR'
  warm_up: True
  params:
    factor: 0.2
    patience: 10

transform:
  name: 's_0627/sin_512_final_hflip_cut0_ssr7_r30'
#  val_name: ''
  num_preprocessor: 8
  size: 512
